name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    strategy:
      matrix:
        go-version:
          - 1.15.x
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Run tests
      run: make test
  
    - name: Install
      run: make install

  golangci-lint:
    name: Lint
    strategy:
      matrix:
        go-version:
          - 1.15.x
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.37
        skip-go-installation: true
